version: '3'
services:
  # node-app:
  #   build: .
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: panthon
      MYSQL_DATABASE: panthon
      MYSQL_USER: panthon
      MYSQL_PASSWORD: panthon
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: panthon
